### ISSUE TITLE
Add styles and animation to 'Why Should You Choose Us?' Cards

### ISSUE THREAD

**Issue by wkan17012021** [KYKY62/RestauranWeb-HTML#1]

**Comment by wkan17012021** [comment]
Hi KYKY62, cool site. 
Please can I suggest a contribution: I would like to make the card components a bit more styled.
I was thinking adding a nicer box-shadow, border-animation and colour to the cards if that's ok? Would it be possible to assign this to me using the Hacktoberfest 2022 tag? 
![image](https://user-images.githubusercontent.com/82063817/194958726-15afe733-066f-4273-8af8-6abfa7298f28.png)

**Comment by KYKY62** [comment]
thank you , you can contribute now .
i already take hacktoberfest labels

**Comment by wkan17012021** [comment]
Hi @KYKY62 , left a PR for review. Thanks!
