### ISSUE TITLE
Add same styling on 'Why Should Choose Us?' to Cards for 'Restaurant Near You'

### ISSUE THREAD

**Issue by wkan17012021** [KYKY62/RestauranWeb-HTML#3]
Apply box-shadow and hover state styles to restaurant image cards to maintain a consistent styling across the page. Please assign with Hacktoberfest tag, please 🙏🏼

**Comment by KYKY62** [comment]
okay, you can pr now

**Comment by wkan17012021** [comment]
PR submitted
