### ISSUE TITLE
Fix colour contrast issues (web accessibility)

### ISSUE THREAD

**Issue by wkan17012021** [KYKY62/RestauranWeb-HTML#4]
Running an accessibility web extension like axe DevTools reveals the webpage to have multiple non-conformance with WCAG 2 AA colour contrast threshold. Change the hex code colours so that at least WCAG AA colour contrast can be achieved. 

![Screenshot 2022-10-13 at 23 15 26](https://user-images.githubusercontent.com/82063817/195721236-780d5c34-7659-4d7c-ad15-a2370c398e68.png)

![Screenshot 2022-10-13 at 23 15 39](https://user-images.githubusercontent.com/82063817/195721244-d532c6c7-1ee4-49ac-aabe-f7f309d0d184.png)

**Comment by wkan17012021** [comment]
Please assign to me w/ Hacktoberfest tag please 🙏🏼

**Comment by KYKY62** [comment]
okay, you can pr too

**Comment by wkan17012021** [comment]
Thanks, PR submitted for this issue 😃
